<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VsaTemplate.TestAppHost</RootNamespace>
    <AssemblyName>VsaTemplate.TestAppHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.SqLite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\..\src\VsaTemplate.Shared\VsaTemplate.Shared.csproj"
      IsAspireProjectResource="false"
    />
  </ItemGroup>
</Project>
