<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>VsaTemplate</RootNamespace>
    <AssemblyName>VsaTemplate</AssemblyName>
    <OpenApiDocumentsDirectory>./wwwroot/openapi/</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--file-name v1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>

  <!--#if (false)-->
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);AddExamples</DefineConstants>
  </PropertyGroup>
  <!--#endif-->

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\openapi\" />
    <Folder Include="Features" />
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Events\" />
    <Folder Include="Infrastructure\Database\Configurations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VsaTemplate.ServiceDefaults\VsaTemplate.ServiceDefaults.csproj" />
    <ProjectReference Include="..\VsaTemplate.Shared\VsaTemplate.Shared.csproj" />
  </ItemGroup>
</Project>
