# TODO: delete packed nuget if it is not a PR ?

name: CI

on: 
  push: 
    branches: ['**'] # runs on all branches, but pack & publish only ran on main branch
    pull_request: 
      branches: [ main ]

jobs:
  ci: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # enable GitHub OIDC token issuance for this job
      
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
          
      - name: Pack Template
        run: dotnet pack nuspec.csproj
        
      - name: Install Template
        run: |
          count=$(ls ./artifacts/package/release/*.nupkg 2>/dev/null | wc -l)
          if [ "$count" -ne 1 ]; then
            echo "::error::More than 1 .nupkg found after packing. Found: $count"
            exit 1
          fi
          dotnet new install ./artifacts/package/release/*.nupkg # TODO: only install current?
        
      - name: Instantiate Template
        run: dotnet new vsa-sln -n CiInstantiated -o ./ci-instantiated
        
      - name: Build Instantiated
        run: dotnet build ./ci-instantiated/CiInstantiated.slnx
        
      - name: Test Instantiated
        run: dotnet test ./ci-instantiated/CiInstantiated.slnx
        
      - name: NuGet Login # uses the id-token to login and retrieve the short-lived API key from NuGet 
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }} # NuGet username as secret
          
      - name: Push to NuGet
        run: dotnet nuget push "./artifacts/package/release/*.nupkg" -k "${{ steps.login.outputs.NUGET_API_KEY }}" -s https://api.nuget.org/v3/index.json