# TODO: delete packed nuget if it is not a PR ?

name: CI

on: 
  push: 
    branches: ['**'] # runs on all branches, but pack & publish only ran on main branch
    pull_request: 
      branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
          
      - name: Pack Template
        run: dotnet pack nuspec.csproj
        
      - name: Install Template
        run: |
          count=$(ls ./artifacts/package/release/*.nupkg 2>/dev/null | wc -l)
          if [ "$count" -ne 1 ]; then
            echo "::error::More than 1 .nupkg found after packing. Found: $count"
            exit 1
          fi
          dotnet new install ./artifacts/package/release/*.nupkg # TODO: only install current?
        
      - name: Instantiate Template
        run: dotnet new vsa-sln -n CiInstantiated -o ./ci-instantiated
        
      - name: Build Instantiated
        run: dotnet build ./ci-instantiated/CiInstantiated.slnx
        
      - name: Test Instantiated
        run: dotnet test ./ci-instantiated/CiInstantiated.slnx