<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VsaTemplate.Tests</RootNamespace>
    <AssemblyName>VsaTemplate.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
